version: '3.4'

services:
  XDelivered.Starter.Core.CosmosDb.website:
    image: ${DOCKER_REGISTRY}xdeliveredwebsite
    build:
      context: .
      dockerfile: XDelivered.Starter.Core.CosmosDb.Website/Dockerfile
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
    environment:
      - MONGODB_DATABASE=xdelivered